// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NS_alias$$atNewNamespace from "@testrepo/new-namespace/src/NS_alias.mjs";

function log() {
  [
    "a",
    "b"
  ].forEach(prim => {
    console.log(prim);
  });
}

console.log(NS_alias$$atNewNamespace.hello_world());

export {
  log,
}
/*  Not a pure module */
