// Generated by ReScript, PLEASE EDIT WITH CARE


let Path = {};

let Process = {};

let Fs = {};

let Buffer = {};

let ChildProcess = {};

let OS = {};

let URL = {};

export {
  Path,
  Process,
  Fs,
  Buffer,
  ChildProcess,
  OS,
  URL,
}
/* No side effect */
