// Generated by ReScript, PLEASE EDIT WITH CARE

import * as A$A from "a/src/A.res.js";
import * as B$B from "b/src/B.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function C(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx(A$A.make, {}),
      JsxRuntime.jsx(B$B.make, {})
    ]
  });
}

let make = C;

export {
  make,
}
/* A-A Not a pure module */
