// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Foo from "Foo";

let React = {};

let Test = {};

function test(className) {
  return Foo;
}

export {
  React,
  Test,
  test,
}
/* Foo Not a pure module */
