// Generated by ReScript, PLEASE EDIT WITH CARE


function mm(x) {
  return make({
    b: !x.b
  });
}

function make(props) {
  return mm({
    b: props.b
  });
}

let Rec = {
  make: make,
  mm: mm
};

export {
  Rec,
}
/* No side effect */
