// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Stdlib from "rescript/lib/es6/Stdlib.js";
import * as Stdlib_Exn from "rescript/lib/es6/Stdlib_Exn.js";
import * as Primitive_exceptions from "rescript/lib/es6/Primitive_exceptions.js";

function panicTest() {
  let caught;
  try {
    caught = Stdlib.panic("uh oh");
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
      caught = err._1.message;
    } else {
      throw err;
    }
  }
  Test.run([
    [
      "Core_ErrorTests.res",
      6,
      22,
      43
    ],
    "Should resolve test"
  ], caught, (prim0, prim1) => prim0 === prim1, "Panic! uh oh");
}

panicTest();

export {
  panicTest,
}
/*  Not a pure module */
