// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let eq = Primitive_object.equal;

Test.run([
  [
    "Core_RegExpTest.res",
    5,
    13,
    33
  ],
  "RegExp.flags basic"
], new RegExp("\\w+", "gi").flags, eq, "gi");

Test.run([
  [
    "Core_RegExpTest.res",
    13,
    13,
    35
  ],
  "RegExp.flags sorting"
], new RegExp("\\w+", "igd").flags, eq, "dgi");

Test.run([
  [
    "Core_RegExpTest.res",
    20,
    20,
    40
  ],
  "RegExp.flags empty"
], new RegExp("\\w+").flags, eq, "");

export {
  eq,
}
/*  Not a pure module */
