#!/usr/bin/env node

// @ts-check

// TODO: Use Yarn's constraints instead.

import fs from "node:fs";

const packageSpec = JSON.parse(
  fs.readFileSync(new URL("../package.json", import.meta.url), "utf-8"),
);
const { name, version } = packageSpec;

/**
 * @param {string} specPath
 * @param {string} version
 */
function setVersion(specPath, version) {
  const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
  spec.version = version;
  fs.writeFileSync(specPath, JSON.stringify(spec, null, 2) + "\n", "utf8");
}

setVersion("./packages/std/package.json", version);
setVersion("./packages/@rescript/linux-x64/package.json", version);
setVersion("./packages/@rescript/linux-arm64/package.json", version);
setVersion("./packages/@rescript/darwin-x64/package.json", version);
setVersion("./packages/@rescript/darwin-arm64/package.json", version);
setVersion("./packages/@rescript/win32-x64/package.json", version);

fs.writeFileSync(
  "./compiler/common/bs_version.ml",
  `(* Copyright (C) 2015-2016 Bloomberg Finance L.P.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * In addition to the permissions granted to you by the LGPL, you may combine
 * or link a "work that uses the Library" with a publicly distributed version
 * of this file to produce a combined library or application, then distribute
 * that combined work under the terms of your choosing, with no requirement
 * to comply with the obligations normally placed on you by section 4 of the
 * LGPL version 3 (or the corresponding section of a later version of the LGPL
 * should you choose to use a later version).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. *)
let version = "${version}"
let header = "// Generated by ReScript, PLEASE EDIT WITH CARE"
let package_name = ref "${name}"
`,
  "utf8",
);
