// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";

let schema = S.schema(s => ({
  foo: s.m(S.string)
}));

let foo = S.parseOrThrow("{ \"foo\": \"bar\" }", schema);

console.log(foo);

export {
  schema,
  foo,
}
/* schema Not a pure module */
