// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function testTuple(param) {
  return param[0] + param[1] | 0;
}

function computeArea(param) {
  return (param[0] * param[1] | 0) * Belt_Option.mapWithDefault(param[2], 1, n => n) | 0;
}

function computeAreaWithIdent(param) {
  return (param[0] * param[1] | 0) * Belt_Option.mapWithDefault(param[2], 1, n => n) | 0;
}

function computeAreaNoConverters(param) {
  return param[0] * param[1] | 0;
}

function coord2d(x, y) {
  return [
    x,
    y,
    undefined
  ];
}

function getFirstName(param) {
  return param[0].name;
}

function marry(first, second) {
  return [
    first,
    second
  ];
}

function changeSecondAge(param) {
  let second = param[1];
  return [
    param[0],
    {
      name: second.name,
      age: second.age + 1 | 0
    }
  ];
}

let origin = [
  0,
  0,
  0
];

export {
  testTuple,
  origin,
  computeArea,
  computeAreaWithIdent,
  computeAreaNoConverters,
  coord2d,
  getFirstName,
  marry,
  changeSecondAge,
}
/* No side effect */
