// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function getNow() {
  return new Promise((res, param) => {
    setTimeout(() => res(new Date()), 1000);
  });
}

async function make(param) {
  let now = await getNow();
  return <div>
    <p>
      {now.toLocaleString()}
    </p>
  </div>;
}

let Async_jsx$Foo = make;

let Foo = {
  make: Async_jsx$Foo
};

function Async_jsx$Bar(props) {
  return <div>
    <Foo.make />
  </div>;
}

let Bar = {
  make: Async_jsx$Bar
};

export {
  getNow,
  Foo,
  Bar,
}
/* react/jsx-runtime Not a pure module */
