// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Dict from "rescript/lib/es6/Stdlib_Dict.js";

let someString = "hello";

let createdDict = {
  name: "hello",
  age: "what",
  more: "stuff",
  otherStr: someString
};

let intDict = {
  one: 1,
  two: 2,
  three: 3
};

function inferDictByPattern(dict) {
  if (dict.one === 1 && dict.three === 3 && dict.four === 4) {
    dict["five"] = 5;
    return;
  }
  if (dict.two !== 1) {
    console.log("not one");
  } else {
    console.log("two");
  }
}

function constrainedAsDict(dict) {
  if (dict.one !== 1) {
    console.log("not one");
  } else {
    console.log("one");
  }
}

let PatternMatching = {
  inferDictByPattern: inferDictByPattern,
  constrainedAsDict: constrainedAsDict
};

let dict = {
  key1: 1,
  key2: undefined
};

if (Stdlib_Dict.has(dict, "key1") !== true) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "DictTests.res",
      43,
      2
    ],
    Error: new Error()
  };
}

if (Stdlib_Dict.has(dict, "key2") !== true) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "DictTests.res",
      44,
      2
    ],
    Error: new Error()
  };
}

if (Stdlib_Dict.has(dict, "key3") !== false) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "DictTests.res",
      45,
      2
    ],
    Error: new Error()
  };
}

let DictHas = {
  dict: dict
};

let three = 3;

export {
  someString,
  createdDict,
  three,
  intDict,
  PatternMatching,
  DictHas,
}
/*  Not a pure module */
