// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js from "rescript/lib/es6/Js.js";

let match = Js.undefinedToOption(typeof __DEV__ === "undefined" ? undefined : __DEV__);

if (match !== undefined) {
  console.log("dev mode");
} else {
  console.log("production mode");
}

/* match Not a pure module */
