// Generated by ReScript, PLEASE EDIT WITH CARE


let match = typeof __DEV__ === "undefined" ? undefined : __DEV__;

if (match !== undefined) {
  console.log("dev mode");
} else {
  console.log("production mode");
}

/* match Not a pure module */
