// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "rescript/lib/es6/Stdlib_Int.js";

let group = {
  nested: {}
};

function fn(str) {
  group.nested.field = Stdlib_Int.fromString(str, undefined);
}

let WithNestedMutableFields = {
  group: group,
  fn: fn
};

let p = [
  {
    field: 2
  },
  ""
];

let x = p[0];

let y = p[0];

let NoOptionalFields = {
  p: p,
  x: x,
  y: y
};

export {
  WithNestedMutableFields,
  NoOptionalFields,
}
/* No side effect */
