// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Lazy from "rescript/lib/es6/Stdlib_Lazy.js";

function fix() {
  return {
    TAG: "Fix",
    _0: Stdlib_Lazy.from_fun(fix)
  };
}

function unfixLeak(_f) {
  while (true) {
    let f = _f;
    _f = Stdlib_Lazy.force(f._0);
    continue;
  };
}

function unfix(p) {
  while (true) {
    let h = p.contents;
    p.contents = Stdlib_Lazy.force(h._0);
  };
}

export {
  fix,
  unfixLeak,
  unfix,
}
/* No side effect */
