// Generated by ReScript, PLEASE EDIT WITH CARE


function x(url) {
  if (url === 0) {
    return "start";
  }
  switch (url.hd) {
    case "login" :
      if (url.tl !== 0) {
        return "start";
      } else {
        return "login";
      }
    case "start" :
      return "start";
    default:
      return "start";
  }
}

export {
  x,
}
/* No side effect */
