// Generated by ReScript, PLEASE EDIT WITH CARE


let myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
};

let T0;

if (myList !== 0) {
  T0 = {
    myList: myList,
    head: 1,
    tail: myList.tl
  };
} else {
  throw {
    RE_EXN_ID: "Match_failure",
    _1: [
      "gpr_4632.res",
      6,
      6
    ],
    Error: new Error()
  };
}

let myList$1 = {
  hd: [
    1,
    2,
    3
  ],
  tl: /* [] */0
};

let T1;

if (myList$1 !== 0) {
  if (/* [] */0 !== 0) {
    T1 = {
      myList: myList$1,
      h0: myList$1.hd,
      h1: /* [] */(0).hd,
      h2: /* [] */(0).tl
    };
  } else {
    throw {
      RE_EXN_ID: "Match_failure",
      _1: [
        "gpr_4632.res",
        12,
        6
      ],
      Error: new Error()
    };
  }
} else {
  throw {
    RE_EXN_ID: "Match_failure",
    _1: [
      "gpr_4632.res",
      12,
      6
    ],
    Error: new Error()
  };
}

export {
  T0,
  T1,
}
/* T0 Not a pure module */
