// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "@rescript/runtime/lib/es6/Js_undefined.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

if (!Primitive_object.equal(Primitive_option.fromNullable(""), "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      2,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(Js_undefined.toOption(""), "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      3,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal(Primitive_option.fromNull(""), "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      4,
      2
    ],
    Error: new Error()
  };
}

/*  Not a pure module */
