// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Lazy from "@rescript/runtime/lib/es6/Stdlib_Lazy.js";

let lazy1 = Stdlib_Lazy.make(() => {
  console.log("Hello, lazy");
  return 1;
});

let lazy2 = Stdlib_Lazy.make(() => 3);

console.log(lazy1, lazy2);

let la = Stdlib_Lazy.get(lazy1);

let lb = Stdlib_Lazy.get(lazy2);

console.log(la, lb);

export {
  lazy1,
  lazy2,
  la,
  lb,
}
/* lazy1 Not a pure module */
