// Generated by ReScript, PLEASE EDIT WITH CARE


function doStuffWithResult(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: "hello"
    };
  } else {
    return {
      TAG: "Error",
      _0: "InvalidString"
    };
  }
}

function doNextStuffWithResult(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: "hello"
    };
  } else {
    return {
      TAG: "Error",
      _0: "InvalidNext"
    };
  }
}

function getXWithResult(s) {
  let e = doStuffWithResult(s);
  if (e.TAG !== "Ok") {
    return e;
  }
  let y = e._0;
  let e$1 = doNextStuffWithResult(y);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: e$1._0 + y
    };
  } else {
    return e$1;
  }
}

let x = getXWithResult("s");

let someResult;

someResult = x.TAG === "Ok" ? x._0 : (
    x._0 === "InvalidNext" ? "nope!" : "nope"
  );

function doStuffWithOption(s) {
  if (s === "s") {
    return "hello";
  }
  
}

function doNextStuffWithOption(s) {
  if (s === "s") {
    return "hello";
  }
  
}

function getXWithOption(s) {
  let x = doStuffWithOption(s);
  if (x === undefined) {
    return x;
  }
  let x$1 = doNextStuffWithOption(x);
  if (x$1 !== undefined) {
    return x$1 + x;
  } else {
    return x$1;
  }
}

let x$1 = getXWithOption("s");

let someOption = x$1 !== undefined ? x$1 : "nope";

async function doStuffResultAsync(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: {
        s: "hello"
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "FetchError"
    };
  }
}

async function decodeResAsync(res) {
  let match = res.s;
  if (match === "s") {
    return {
      TAG: "Ok",
      _0: res.s
    };
  } else {
    return {
      TAG: "Error",
      _0: "DecodeError"
    };
  }
}

async function getXWithResultAsync(s) {
  let e = await doStuffResultAsync(s);
  if (e.TAG !== "Ok") {
    return e;
  }
  let res = e._0;
  console.log(res.s);
  let e$1 = await decodeResAsync(res);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: e$1._0
    };
  } else {
    return e$1;
  }
}

function returnsAliasOnFirstError(s) {
  let e = doStuffWithResult(s);
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: "ok"
    };
  } else {
    return e;
  }
}

function returnsAliasOnSecondError(s) {
  let e = doStuffWithResult(s);
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = doNextStuffWithResult(e._0);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: "ok"
    };
  } else {
    return e$1;
  }
}

function returnsAliasOnOk(s) {
  let x = doStuffWithResult(s);
  if (x.TAG === "Ok") {
    return x;
  } else {
    return {
      TAG: "Error",
      _0: "GotError"
    };
  }
}

export {
  doStuffWithResult,
  doNextStuffWithResult,
  getXWithResult,
  someResult,
  doStuffWithOption,
  doNextStuffWithOption,
  getXWithOption,
  someOption,
  doStuffResultAsync,
  decodeResAsync,
  getXWithResultAsync,
  returnsAliasOnFirstError,
  returnsAliasOnSecondError,
  returnsAliasOnOk,
}
/* x Not a pure module */
