// Generated by ReScript, PLEASE EDIT WITH CARE


let a1 = {
  TAG: 3,
  _0: 10
};

let b1 = {
  TAG: "3",
  _0: 10
};

let a2 = "x";

let b2 = {
  TAG: "x",
  _0: 10
};

export {
  a1,
  b1,
  a2,
  b2,
}
/* No side effect */
