// Generated by ReScript, PLEASE EDIT WITH CARE


let options = {
  extra: {
    name: "test",
    superExtra: {
      age: 2222
    },
    otherExtra: {
      test: true,
      anotherInlined: {
        record: true
      }
    }
  }
};

export {
  options,
}
/* No side effect */
