// Generated by ReScript, PLEASE EDIT WITH CARE


let options = {
  extra: {
    name: "test",
    superExtra: {
      age: 2222
    },
    otherExtra: {
      test: true,
      anotherInlined: {
        record: true
      }
    }
  }
};

let opts2 = {
  extra: {
    name: "test",
    superExtra: {
      age: "1234"
    },
    otherExtra: {
      test: true,
      anotherInlined: {
        record: true
      }
    }
  }
};

export {
  options,
  opts2,
}
/* No side effect */
