// Generated by ReScript, PLEASE EDIT WITH CARE


function f1(action) {
  if (typeof action === "object") {
    switch (action.TAG) {
      case "WithPayload5" :
      case "WithPayload6" :
      case "WithPayload7" :
      case "WithPayload8" :
        console.log("hello");
        break;
    }
  }
  return 42;
}

function f2(action) {
  if (typeof action === "object") {
    switch (action.TAG) {
      case "WithPayload5" :
      case "WithPayload6" :
      case "WithPayload7" :
      case "WithPayload8" :
        console.log("hello");
        break;
    }
  }
  return 42;
}

export {
  f1,
  f2,
}
/* No side effect */
