// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

let x6 = {
  x: 42
};

let x7 = [
  1,
  2,
  3
];

let x8 = () => {};

let x10 = null;

let x11 = Primitive_option.some(undefined);

let x20 = null;

let x21 = new Date();

let x22 = /test/;

let x1 = "hello";

let x2 = 1;

let x3 = {
  TAG: "Ok",
  _0: "hi"
};

let x4 = "polyvar";

let x5 = {
  x: 42
};

let x12 = "test";

export {
  x1,
  x2,
  x3,
  x4,
  x5,
  x6,
  x7,
  x8,
  x10,
  x11,
  x12,
  x20,
  x21,
  x22,
}
/* x20 Not a pure module */
