// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function boolean(val1, val2) {
  let a = val1;
  let b = val2;
  if (b || a) {
    return "a";
  } else {
    return "b";
  }
}

function $$null(val1, val2) {
  let a = Primitive_option.some(val1);
  let b = Primitive_option.some(val2);
  let tmp = Primitive_option.valFromOption(b);
  if (tmp !== null && tmp !== undefined) {
    return "a";
  }
  tmp === null;
  let tmp$1 = Primitive_option.valFromOption(a);
  if (tmp$1 == null) {
    return "b";
  } else {
    return "a";
  }
}

export {
  boolean,
  $$null,
}
/* No side effect */
