// Generated by ReScript, PLEASE EDIT WITH CARE


function add(x) {
  return (y, z) => (x + y | 0) + z | 0;
}

function f(u) {
  let f$1 = add(u);
  return extra => f$1(1, extra);
}

function add$1(a, b) {
  return a + b | 0;
}

function add5(extra) {
  return 5 + extra | 0;
}

export {
  f,
  add$1 as add,
  add5,
}
/* No side effect */
