// Generated by ReScript, PLEASE EDIT WITH CARE


function bad1(schema) {
  if (schema.format !== undefined) {
    return "int32";
  } else {
    return "default";
  }
}

function good1(schema) {
  if (schema.format !== undefined) {
    return "int32";
  } else {
    return "default";
  }
}

let SingleFormatCase = {
  bad1: bad1,
  good1: good1
};

function bad2(schema) {
  let match = schema.format;
  if (match !== undefined) {
    if (match === "Int32") {
      return "int32";
    } else {
      return "dd";
    }
  } else {
    return "default";
  }
}

function good2(schema) {
  let match = schema.format;
  if (match !== undefined) {
    if (match === "Int32") {
      return "int32";
    } else {
      return "dd";
    }
  } else {
    return "default";
  }
}

let MultipleFormatCase = {
  bad2: bad2,
  good2: good2
};

export {
  SingleFormatCase,
  MultipleFormatCase,
}
/* No side effect */
