// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mt from "./mt.mjs";

let suites = {
  contents: /* [] */0
};

let test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

function then(a, b) {
  console.log("no inline");
  return (a * a | 0) + (b * b | 0) | 0;
}

eq("File \"then_mangle_test.res\", line 14, characters 3-10", then(1, 2), 5);

Mt.from_pair_suites("then_mangle_test.res", suites.contents);

/*  Not a pure module */
